version: '3'
services:
  auth-db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
    env_file:
      - .env
    ports:
      - '5433:5432'

  user-service-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: user-service-db
    env_file:
      - .env
    ports:
      - '5434:5432'

  book-service-db:
    image: postgres:15
    container_name: book-service-db
    environment:
      POSTGRES_DB: book-service-db
    env_file:
      - .env
    ports:
      - '5435:5432'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    container_name: zookeeper
    networks:
      - bookly-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    networks:
      - bookly-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:6.0
    container_name: book-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: book-db
    command: ["--replSet", "rs0"]
    volumes:
      - mongo-data:/data/db

networks:
  bookly-network:
    driver: bridge

volumes:
  mongo-data: