version: '3'
services:
  auth-db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
    env_file:
      - .env
    ports:
      - '5433:5432'

  user-service-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: user-service-db
    env_file:
      - .env
    ports:
      - '5434:5432'

  book-service-db:
    image: postgres:15
    container_name: book-service-db
    environment:
      POSTGRES_DB: book-service-db
    env_file:
      - .env
    ports:
      - '5435:5432'