spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth-service/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/profile/**
        - id: book-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/book-service/**

      default-filters:
        - AddResponseHeader=X-Gateway, SpringCloud
server:
  port: 8080
security:
  jwt:
    secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody