spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/book-service-db
    username: "${POSTGRES_DB_USERNAME}"
    password: "${POSTGRES_DB_PASSWORD}"
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
security:
  jwt:
    secret-key: verysecretkeyohmygodwhyisitsosecretdonttellanybody